### ISSUE TITLE
Not displayed in Store

### ISSUE THREAD

**Issue by Unrud** [flathub/eu.planete_kraus.Tarot#5]
The app is missing: https://flathub.org/apps/details/eu.planete_kraus.Tarot
I think this is caused by one or multiple of the following issues:

  * The icon name should be ``eu.planete_kraus.Tarot``:
https://framagit.org/play-tarot/tarot/blob/80831eb766ad563b50a769c122883df504bb52cb/eu.planete_kraus.Tarot.desktop.in#L7
  * (Icons with a resolution of 64x64 and 128x128 should be provided.)

**Comment by ghost** [comment]
Hello,

I feel bad for being so late.  Sorry for that.  Anyway, thank you very much for your investigations!  I have copied the issue to the gitlab repo, it will be addressed shortly :)

I don't understand why I did not get the notification for a new issue...  Now I have subscribed to the thread.

https://framagit.org/play-tarot/tarot/issues/144

**Comment by ghost** [comment]
OK so this has been corrected in 1.3.3, which has been built on flathub builds: https://flathub.org/builds/#/apps/eu.planete_kraus.Tarot.

Now waiting for the update to be available.

**Comment by ghost** [comment]
The update is available, but the store still reads "app not found".

**Comment by ghost** [comment]
I have sent an email to admins@flathub.org

**Comment by ghost** [comment]
Mmh this is an alias for the flathub-admins.lists.freedesktop.org list, and my message has been filtered out.

**Comment by ghost** [comment]
This looks similar to https://github.com/flathub/linux-store-frontend/issues/181

**Comment by ghost** [comment]
I have modified the appstream data according to the proposed fix in that issue.

**Comment by ghost** [comment]
Now this is fixed.
